name: flutter_k_chart
description: A Flutter K Chart.
version: 1.0.0
homepage: https://github.com/fxwalletOfficial/flutter_k_chart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
